[package]
name = "snes-interpreter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.2.1"
lazy_static = "1.4.0"
rand = "=0.7.3"
sdl2 = "0.34.0"
